var BOOKS = [
  { id:1,   title:'Outwitting the Devil',                    author:'Napoleon Hill',               isbn:'9781640951839', read:true,  genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:2,   title:'You Are a Badass',                        author:'Jen Sincero',                 isbn:'9780762447695', read:true,  genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:3,   title:'The Jordan Rules',                        author:'Sam Smith',                   isbn:'9780671796105', read:true,  genre:'Sports',             why:'', helped:'', notes:'' },
  { id:4,   title:'The Power of Self-Discipline',            author:'Brian Tracy',                 isbn:'9781640950801', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:5,   title:'The Oxygen Advantage',                    author:'Patrick McKeown',             isbn:'9780062349477', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:6,   title:'The Mamba Mentality',                     author:'Kobe Bryant',                 isbn:'9780374201234', read:false, genre:'Sports',             why:'', helped:'', notes:'' },
  { id:7,   title:'Way of the Peaceful Warrior',             author:'Dan Millman',                 isbn:'9780915811908', read:false, genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:8,   title:'The Hard Thing About Hard Things',        author:'Ben Horowitz',                isbn:'9780062273208', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:9,   title:'The Alchemist',                           author:'Paulo Coelho',                isbn:'9780061233500', read:false, genre:'Fiction',            why:'', helped:'', notes:'' },
  { id:10,  title:'Eleven Rings',                            author:'Phil Jackson',                isbn:'9780143125341', read:false, genre:'Sports',             why:'', helped:'', notes:'' },
  { id:11,  title:'Driven',                                  author:'Douglas Brackmann',           isbn:'9781544507903', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:12,  title:'How Will You Measure Your Life',          author:'Clayton Christensen',         isbn:'9780062102416', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:13,  title:'Loving What Is',                          author:'Byron Katie',                 isbn:'9781400045372', read:true,  genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:14,  title:'Atomic Habits',                           author:'James Clear',                 isbn:'9780735211292', read:true,  genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:15,  title:'Talent Is Overrated',                     author:'Geoff Colvin',                isbn:'9781591842248', read:false, genre:'Psychology',         why:'', helped:'', notes:'' },
  { id:16,  title:'How Successful People Lead',              author:'John C. Maxwell',             isbn:'9781599953625', read:false, genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:17,  title:'Tribes',                                  author:'Seth Godin',                  isbn:'9781591842330', read:true,  genre:'Business',           why:'', helped:'', notes:'' },
  { id:18,  title:'The Power of Habit',                      author:'Charles Duhigg',              isbn:'9780812981605', read:true,  genre:'Psychology',         why:'', helped:'', notes:'' },
  { id:19,  title:'Dare to Lead',                            author:'Bren\u00e9 Brown',            isbn:'9780399592522', read:true,  genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:20,  title:'The Client',                              author:'John Grisham',                isbn:'9780440213529', read:false, genre:'Fiction',            why:'', helped:'', notes:'' },
  { id:21,  title:'Talk Like TED',                           author:'Carmine Gallo',               isbn:'9781250061539', read:true,  genre:'Business',           why:'', helped:'', notes:'' },
  { id:22,  title:'The Greatest Salesman in the World',      author:'Og Mandino',                  isbn:'9780553277579', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:23,  title:'Sometimes You Win Sometimes You Learn',   author:'John C. Maxwell',             isbn:'9781455587865', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:24,  title:'Grit',                                    author:'Angela Duckworth',            isbn:'9781501111105', read:true,  genre:'Psychology',         why:'', helped:'', notes:'' },
  { id:25,  title:'Zero to One',                             author:'Peter Thiel',                 isbn:'9780804139298', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:26,  title:'Winner\'s Dream',                         author:'Bill McDermott',              isbn:'9781476761596', read:false, genre:'Memoir',             why:'', helped:'', notes:'' },
  { id:27,  title:'The 22 Immutable Laws of Marketing',      author:'Al Ries & Jack Trout',        isbn:'9780887306662', read:false, genre:'Marketing',          why:'', helped:'', notes:'' },
  { id:28,  title:'Ego Is the Enemy',                        author:'Ryan Holiday',                isbn:'9781591847816', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:29,  title:'The Secret',                              author:'Rhonda Byrne',                isbn:'9781582701707', read:true,  genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:30,  title:'Rookie Smarts',                           author:'Liz Wiseman',                 isbn:'9780062322630', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:31,  title:'Instantaneous Personal Magnetism',        author:'Edmund Shaftesbury',          isbn:'',              read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:32,  title:'Man\'s Search for Meaning',               author:'Viktor Frankl',               isbn:'9780807014295', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:33,  title:'Lead Yourself First',                     author:'Raymond Kethledge',           isbn:'9781632866318', read:false, genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:34,  title:'How to Win Friends and Influence People',  author:'Dale Carnegie',              isbn:'9780671027032', read:true,  genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:35,  title:'The Energy Bus',                          author:'Jon Gordon',                  isbn:'9780470100288', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:36,  title:'What to Expect When You\'re Expecting',   author:'Heidi Murkoff',               isbn:'9780761187486', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:37,  title:'Steal Like an Artist',                    author:'Austin Kleon',                isbn:'9780761169253', read:false, genre:'Creativity',         why:'', helped:'', notes:'' },
  { id:38,  title:'Leadership 101',                          author:'John C. Maxwell',             isbn:'9780785264125', read:false, genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:39,  title:'Thinking with Type',                      author:'Ellen Lupton',                isbn:'9781568989693', read:false, genre:'Design',             why:'', helped:'', notes:'' },
  { id:40,  title:'Why We Sleep',                            author:'Matthew Walker',              isbn:'9781501144318', read:false, genre:'Science',            why:'', helped:'', notes:'' },
  { id:41,  title:'The Talent Code',                         author:'Daniel Coyle',                isbn:'9780553806847', read:true,  genre:'Psychology',         why:'', helped:'It taught me how I learn and how to learn better.', notes:'' },
  { id:42,  title:'As a Man Thinketh',                       author:'James Allen',                 isbn:'9780486452838', read:true,  genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:43,  title:'Drawing on the Powers of Heaven',         author:'Grant Von Harrison',          isbn:'0961636807',    read:true,  genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:44,  title:'Head Strong',                             author:'Dave Asprey',                 isbn:'9780062652416', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:45,  title:'Bluefishing',                             author:'Steve Sims',                  isbn:'9781501152511', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:46,  title:'Food Rules',                              author:'Michael Pollan',              isbn:'9780143116387', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:47,  title:'The Power of Awareness',                  author:'Neville Goddard',             isbn:'9781614270935', read:true,  genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:48,  title:'The Monk Who Sold His Ferrari',           author:'Robin Sharma',                isbn:'9780062515674', read:true,  genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:49,  title:'Conscious Leadership',                    author:'John Mackey',                 isbn:'9780593083628', read:false, genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:50,  title:'Leadership and Self-Deception',           author:'The Arbinger Institute',      isbn:'9781576759776', read:false, genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:51,  title:'Be Where Your Feet Are',                  author:'Scott O\'Neil',               isbn:'9781250769886', read:true,  genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:52,  title:'The Obstacle Is the Way',                 author:'Ryan Holiday',                isbn:'9781591846352', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:53,  title:'Win or Learn',                            author:'John Kavanagh',               isbn:'9780241257562', read:true,  genre:'Sports',             why:'', helped:'', notes:'' },
  { id:54,  title:'Extreme Ownership',                       author:'Jocko Willink & Leif Babin',  isbn:'9781250183866', read:false, genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:55,  title:'Sacred Cow',                              author:'Diana Rodgers & Robb Wolf',   isbn:'9781948836913', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:56,  title:'The Inner Game of Tennis',                author:'W. Timothy Gallwey',          isbn:'9780679778318', read:false, genre:'Sports',             why:'', helped:'', notes:'' },
  { id:57,  title:'Antifragile',                             author:'Nassim Nicholas Taleb',       isbn:'9780812979688', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:58,  title:'KG: A to Z',                              author:'Kevin Garnett',               isbn:'9781476775104', read:false, genre:'Sports',             why:'', helped:'', notes:'' },
  { id:59,  title:'The Science of Getting Rich',             author:'Wallace D. Wattles',          isbn:'9781585426010', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:60,  title:'Happy Sexy Millionaire',                  author:'Steven Bartlett',             isbn:'9780008386375', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:61,  title:'The Practice of Groundedness',            author:'Brad Stulberg',               isbn:'9780593329009', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:62,  title:'Peak Performance',                        author:'Brad Stulberg & Steve Magness', isbn:'9781623367930', read:false, genre:'Science',         why:'', helped:'', notes:'' },
  { id:63,  title:'Why I Stand',                             author:'Jonathan Isaac',              isbn:'9780593236826', read:false, genre:'Memoir',             why:'', helped:'', notes:'' },
  { id:64,  title:'The Map of Consciousness Explained',      author:'David R. Hawkins',            isbn:'9781401952358', read:false, genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:65,  title:'Nutrition and Physical Degeneration',     author:'Weston A. Price',             isbn:'9780916764203', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:66,  title:'Empire of Pain',                          author:'Patrick Radden Keefe',        isbn:'9780385545686', read:false, genre:'Non-Fiction',        why:'', helped:'', notes:'' },
  { id:67,  title:'The End of Alzheimer\'s',                 author:'Dale Bredesen',               isbn:'9780735216204', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:68,  title:'The 80/20 Principle',                     author:'Richard Koch',                isbn:'9780385491747', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:69,  title:'Peaks and Valleys',                       author:'Spencer Johnson',             isbn:'9781501108716', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:70,  title:'Leaders Eat Last',                        author:'Simon Sinek',                 isbn:'9781591845324', read:false, genre:'Leadership',         why:'', helped:'', notes:'' },
  { id:71,  title:'Things That Matter',                      author:'Charles Krauthammer',         isbn:'9780385349192', read:false, genre:'Non-Fiction',        why:'', helped:'', notes:'' },
  { id:72,  title:'Built to Last',                           author:'Jim Collins & Jerry Porras',  isbn:'9780060516406', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:73,  title:'Outlive',                                 author:'Peter Attia',                 isbn:'9780593236598', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:74,  title:'The Book on Tax Strategies',              author:'Amanda Han & Matthew MacFarland', isbn:'9780990711766', read:false, genre:'Finance',        why:'', helped:'', notes:'' },
  { id:75,  title:'Do Hard Things',                          author:'Steve Magness',               isbn:'9780063042766', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:76,  title:'$100M Offers',                            author:'Alex Hormozi',                isbn:'9781737475705', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:77,  title:'One Up on Wall Street',                   author:'Peter Lynch',                 isbn:'9780743200400', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:78,  title:'The Mom Test',                            author:'Rob Fitzpatrick',             isbn:'9781492180746', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:79,  title:'The Wealth of Nations',                   author:'Adam Smith',                  isbn:'9780679783367', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:80,  title:'Relentless',                              author:'Tim S. Grover',               isbn:'9781476714202', read:true,  genre:'Sports',             why:'', helped:'', notes:'' },
  { id:81,  title:'The Playmaker\'s Advantage',              author:'Leonard Zaichkowsky',         isbn:'9781501181870', read:false, genre:'Sports',             why:'', helped:'', notes:'' },
  { id:82,  title:'Discipline Is Destiny',                   author:'Ryan Holiday',                isbn:'9780593191699', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:83,  title:'Skin in the Game',                        author:'Nassim Nicholas Taleb',       isbn:'9780425284643', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:84,  title:'The Strategy of Conflict',                author:'Thomas C. Schelling',         isbn:'9780674840317', read:false, genre:'Non-Fiction',        why:'', helped:'', notes:'' },
  { id:85,  title:'Buyology',                                author:'Martin Lindstrom',            isbn:'9780385523899', read:false, genre:'Marketing',          why:'', helped:'', notes:'' },
  { id:86,  title:'Build the Life You Want',                 author:'Arthur C. Brooks',            isbn:'9780593545409', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:87,  title:'The Miracle of Mindfulness',              author:'Thich Nhat Hanh',             isbn:'9780807012390', read:false, genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:88,  title:'The Happiness Advantage',                 author:'Shawn Achor',                 isbn:'9780307591555', read:false, genre:'Psychology',         why:'', helped:'', notes:'' },
  { id:89,  title:'The Big Fat Surprise',                    author:'Nina Teicholz',               isbn:'9781451624427', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:90,  title:'The Formula',                             author:'Albert-L\u00e1szl\u00f3 Barab\u00e1si', isbn:'9780316505499', read:false, genre:'Science',  why:'', helped:'', notes:'' },
  { id:91,  title:'The Body Keeps the Score',                author:'Bessel van der Kolk',         isbn:'9780143127741', read:false, genre:'Psychology',         why:'', helped:'', notes:'' },
  { id:92,  title:'The Black Swan',                          author:'Nassim Nicholas Taleb',       isbn:'9780812973815', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:93,  title:'Thinking, Fast and Slow',                 author:'Daniel Kahneman',             isbn:'9780374533557', read:false, genre:'Psychology',         why:'', helped:'', notes:'' },
  { id:94,  title:'Purple Cow',                              author:'Seth Godin',                  isbn:'9781591843177', read:false, genre:'Marketing',          why:'', helped:'', notes:'' },
  { id:95,  title:'The Future Is Faster Than You Think',     author:'Peter Diamandis',             isbn:'9781982109660', read:false, genre:'Science',            why:'', helped:'', notes:'' },
  { id:96,  title:'The E-Myth Revisited',                    author:'Michael E. Gerber',           isbn:'9780887307287', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:97,  title:'The Psychology of Money',                 author:'Morgan Housel',               isbn:'9780857197689', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:98,  title:'Focus on What Matters',                   author:'',                            isbn:'',              read:true,  genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:99,  title:'Mastery',                                 author:'Robert Greene',               isbn:'9780670024964', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:100, title:'The Daily Laws',                          author:'Robert Greene',               isbn:'9780593299227', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:101, title:'Spontaneous Healing',                     author:'Andrew Weil',                 isbn:'9780449910641', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:102, title:'The Way of the Superior Man',             author:'David Deida',                 isbn:'9781591792574', read:false, genre:'Self-Help',          why:'', helped:'', notes:'' },
  { id:103, title:'Fatal Conveniences',                      author:'Darin Olien',                 isbn:'9780063081024', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:104, title:'The Gap and the Gain',                    author:'Dan Sullivan & Benjamin Hardy', isbn:'9781401964368', read:false, genre:'Self-Help',        why:'', helped:'', notes:'' },
  { id:105, title:'The Algebra of Wealth',                   author:'Scott Galloway',              isbn:'9780593714027', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:106, title:'Ikigai',                                  author:'H\u00e9ctor Garc\u00eda & Francesc Miralles', isbn:'9780143130727', read:false, genre:'Philosophy', why:'', helped:'', notes:'' },
  { id:107, title:'Die with Zero',                           author:'Bill Perkins',                isbn:'9780358099765', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:108, title:'Three Magic Words',                       author:'U.S. Andersen',               isbn:'9780879803803', read:false, genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:109, title:'Parallel Universes of Self',              author:'Frederick Dodson',            isbn:'9781456568764', read:false, genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:110, title:'The Invisible Rainbow',                   author:'Arthur Firstenberg',          isbn:'9781603588225', read:false, genre:'Science',            why:'', helped:'', notes:'' },
  { id:111, title:'Virus Mania',                             author:'Torsten Engelbrecht',         isbn:'9781425114671', read:false, genre:'Science',            why:'', helped:'', notes:'' },
  { id:112, title:'The Almanack of Naval Ravikant',          author:'Eric Jorgenson',              isbn:'9781544514215', read:false, genre:'Philosophy',         why:'', helped:'', notes:'' },
  { id:113, title:'Foundations of Machine Learning',         author:'Mehryar Mohri',               isbn:'9780262039406', read:false, genre:'Science',            why:'', helped:'', notes:'' },
  { id:114, title:'The Elements of Statistical Learning',    author:'Trevor Hastie',               isbn:'9780387848570', read:false, genre:'Science',            why:'', helped:'', notes:'' },
  { id:115, title:'The Algorithm Design Manual',             author:'Steven S. Skiena',            isbn:'9783030542559', read:false, genre:'Science',            why:'', helped:'', notes:'' },
  { id:116, title:'Pelvic Power',                            author:'Eric Franklin',               isbn:'9780871272591', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:117, title:'Ultimate Back Fitness and Performance',   author:'Stuart McGill',               isbn:'9780973501810', read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:118, title:'Autobiography of a Yogi',                 author:'Paramahansa Yogananda',       isbn:'9780876120798', read:false, genre:'Spirituality',       why:'', helped:'', notes:'' },
  { id:119, title:'Inside American Education',               author:'Thomas Sowell',               isbn:'9781439107010', read:false, genre:'Non-Fiction',        why:'', helped:'', notes:'' },
  { id:120, title:'Games People Play',                       author:'Eric Berne',                  isbn:'9780345410030', read:false, genre:'Psychology',         why:'', helped:'', notes:'' },
  { id:121, title:'The Trick to Money Is Having Some',       author:'Stuart Wilde',                isbn:'9781561700639', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:122, title:'Unreasonable Hospitality',                author:'Will Guidara',                isbn:'9780593418574', read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:123, title:'10x Is Easier Than 2x',                   author:'Dan Sullivan & Benjamin Hardy', isbn:'9781401969950', read:false, genre:'Self-Help',       why:'', helped:'', notes:'' },
  { id:124, title:'Sacred Hoops',                            author:'Phil Jackson',                isbn:'9781401308810', read:false, genre:'Sports',             why:'', helped:'', notes:'' },
  { id:125, title:'Guts and Grease',                         author:'',                            isbn:'',              read:false, genre:'Non-Fiction',        why:'', helped:'', notes:'' },
  { id:126, title:'Your Health',                             author:'',                            isbn:'',              read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:127, title:'No Money Down Real Estate',               author:'Brandon Turner',              isbn:'9780990711711', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
  { id:128, title:'The Metabolic Maze',                      author:'',                            isbn:'',              read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:129, title:'Ancient Remedies Revived',                author:'',                            isbn:'',              read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:130, title:'Health and Beauty Mastery',               author:'',                            isbn:'',              read:false, genre:'Health & Wellness',  why:'', helped:'', notes:'' },
  { id:131, title:'Barons',                                  author:'',                            isbn:'',              read:false, genre:'Non-Fiction',        why:'', helped:'', notes:'' },
  { id:132, title:'Sponsor Magnet',                          author:'',                            isbn:'',              read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:133, title:'The Science of Scaling',                  author:'',                            isbn:'',              read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:134, title:'Forbidden Business Mindset',              author:'',                            isbn:'',              read:false, genre:'Business',           why:'', helped:'', notes:'' },
  { id:135, title:'Sales Expertise',                         author:'',                            isbn:'',              read:false, genre:'Marketing',          why:'', helped:'', notes:'' },
  { id:136, title:'No Money Down Real Estate',               author:'Brandon Turner',              isbn:'9780990711711', read:false, genre:'Finance',            why:'', helped:'', notes:'' },
];

// Helper: get cover URL from ISBN (Open Library Covers API)
function getBookCover(isbn) {
  if (!isbn) return '';
  return 'https://covers.openlibrary.org/b/isbn/' + isbn + '-M.jpg';
}

// Helper: generate Amazon search link (replace YOUR_TAG with your affiliate tag)
function getAmazonLink(book) {
  var query = encodeURIComponent(book.title + ' ' + book.author);
  return 'https://www.amazon.com/s?k=' + query + '&tag=YOUR_TAG-20';
}

// Pagination
var BOOKS_PER_PAGE = 24;
function getBooksPage(page) {
  var start = page * BOOKS_PER_PAGE;
  return BOOKS.slice(start, start + BOOKS_PER_PAGE);
}
function getTotalBookPages() {
  return Math.ceil(BOOKS.length / BOOKS_PER_PAGE);
}
function getBookById(id) {
  for (var i = 0; i < BOOKS.length; i++) {
    if (BOOKS[i].id === id) return BOOKS[i];
  }
  return null;
}
